#!/bin/bash
#Install the karamba bar weather resources
karamba_weather="karamba-weather"
cd /etc/skel/
tar -xzf /kinneret/packages/src/$karamba_weather.tar.gz
chown knoppix:knoppix .weather
#SCRIPT ENDED
