Document: knrtheme
Title: Debian knrtheme Manual
Author: <insert document author here>
Abstract: This manual describes what knrtheme is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/knrtheme/knrtheme.sgml.gz

Format: postscript
Files: /usr/share/doc/knrtheme/knrtheme.ps.gz

Format: text
Files: /usr/share/doc/knrtheme/knrtheme.text.gz

Format: HTML
Index: /usr/share/doc/knrtheme/html/index.html
Files: /usr/share/doc/knrtheme/html/*.html

  
