Document: l2swim
Title: Debian l2swim Manual
Author: <insert document author here>
Abstract: This manual describes what l2swim is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/l2swim/l2swim.sgml.gz

Format: postscript
Files: /usr/share/doc/l2swim/l2swim.ps.gz

Format: text
Files: /usr/share/doc/l2swim/l2swim.text.gz

Format: HTML
Index: /usr/share/doc/l2swim/html/index.html
Files: /usr/share/doc/l2swim/html/*.html

  
